In [1]:
import numpy as np
import pandas as pd

## Content Based Movie Recommender System

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [4]:
credits.head(3)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [5]:
movies = movies.merge(credits, on='title')

In [6]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [7]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace=True)

In [10]:
movies.duplicated().sum()

0

### Fetching all the genres and keywords of movie

In [11]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [12]:
import ast

In [13]:
def convert(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [14]:
movies['genres'] = movies['genres'].apply(convert)

In [15]:
movies['keywords'] = movies['keywords'].apply(convert)

In [16]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### Fetching top 3 actors form cast

In [17]:
def convert3(obj):
    l = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            l.append(i['name'])
            counter += 1
        else:
            break
    return l

In [18]:
movies['cast'] = movies['cast'].apply(convert3)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### Fetching director from crew

In [20]:
def fetch_director(obj):
    l = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            l.append(i['name'])
            break
    return l

In [21]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

### overview column

In [23]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [24]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

### Transformation

In [26]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(' ', '') for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(' ', '') for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(' ', '') for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(' ', '') for i in x])

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

### tags column

In [28]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [30]:
new_df = movies[['movie_id', 'title', 'tags']]

In [31]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\Acer\AppData\Local\Temp\ipykernel_9248\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [32]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

C:\Users\Acer\AppData\Local\Temp\ipykernel_9248\1380776331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [33]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [34]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

### Stemming

In [44]:
import nltk
from nltk.stem.porter import PorterStemmer

In [45]:
ps = PorterStemmer()

In [46]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [48]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Acer\AppData\Local\Temp\ipykernel_9248\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

### Vectorization

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [50]:
cv = CountVectorizer(max_features=5000, stop_words='english')

In [51]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [52]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [53]:
cv.get_feature_names()

C:\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

### Calculating cosine distances

In [55]:
from sklearn.metrics.pairwise import cosine_similarity

In [58]:
similarity = cosine_similarity(vectors)

In [59]:
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [64]:
def recommend(movie):
    movie_index = new_df[new_df['title']==movie].index[0]
    distances = similarity[movie_index]
    
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [65]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [63]:
new_df.iloc[1216].title

'Aliens vs Predator: Requiem'